# Generated by Django 5.0.1 on 2026-01-14 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_user_managers_alter_user_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Optional user profile picture', null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='district',
            field=models.CharField(blank=True, choices=[('Pune', 'Pune'), ('Mumbai', 'Mumbai'), ('Bangalore', 'Bangalore')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='state',
            field=models.CharField(blank=True, choices=[('Maharashtra', 'Maharashtra'), ('Karnataka', 'Karnataka'), ('Tamil Nadu', 'Tamil Nadu')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='taluka',
            field=models.CharField(blank=True, choices=[('Haveli', 'Haveli'), ('Andheri', 'Andheri'), ('Whitefield', 'Whitefield')], max_length=50),
        ),
    ]
