# Generated by Django 5.0.1 on 2026-01-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_user_profile_picture_alter_user_district_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='village',
            field=models.CharField(blank=True, help_text="Optional: user's village", max_length=255, null=True),
        ),
    ]
