# Generated by Django 5.0.1 on 2026-01-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_user_village'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, help_text='Optional. Letters, digits and @/./+/-/_ only.', max_length=150, null=True, unique=True),
        ),
    ]
