# Generated by Django 5.0.1 on 2026-01-07 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0019_add_crop_category_and_grapes_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='croptype',
            name='plantation_type',
            field=models.CharField(blank=True, help_text='Plantation type for this crop (choices depend on crop category)', max_length=100),
        ),
        migrations.AlterField(
            model_name='croptype',
            name='planting_method',
            field=models.CharField(blank=True, help_text='Planting method for this crop (only for sugarcane)', max_length=100, null=True),
        ),
    ]
