# Generated by Django 5.0.1 on 2026-01-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0020_alter_croptype_plantation_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='croptype',
            name='crop_type',
            field=models.CharField(blank=True, choices=[('Sugarcane', 'Sugarcane'), ('Grapes', 'Grapes'), ('Wheat', 'Wheat'), ('Rice', 'Rice'), ('Cotton', 'Cotton'), ('Corn', 'Corn'), ('Soybean', 'Soybean'), ('Potato', 'Potato'), ('Tomato', 'Tomato'), ('Onion', 'Onion'), ('Other', 'Other')], help_text='Name of the crop type', max_length=100),
        ),
    ]
