# Generated by Django 5.0.1 on 2026-01-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0021_alter_croptype_crop_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='croptype',
            options={'ordering': ['crop_category'], 'verbose_name': 'Crop Type', 'verbose_name_plural': 'Crop Types'},
        ),
        migrations.RemoveField(
            model_name='croptype',
            name='crop_type',
        ),
        migrations.AlterField(
            model_name='croptype',
            name='crop_category',
            field=models.CharField(choices=[('sugarcane', 'Sugarcane'), ('grapes', 'Grapes')], default='sugarcane', help_text='Category of crop (determines which fields to show)', max_length=50),
        ),
    ]
