# Generated by Django 5.0.1 on 2026-01-18 23:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0022_alter_croptype_options_remove_croptype_crop_type_and_more'),
        ('users', '0010_user_village'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='plot',
            name='farms_plot_gat_num_653494_idx',
        ),
        migrations.AlterUniqueTogether(
            name='plot',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='plot',
            constraint=models.UniqueConstraint(fields=('gat_number', 'plot_number', 'village', 'taluka', 'district'), name='unique_plot_global'),
        ),
        migrations.AddConstraint(
            model_name='plot',
            constraint=models.UniqueConstraint(fields=('farmer', 'gat_number', 'plot_number', 'village'), name='unique_plot_per_farmer'),
        ),
    ]
