# Generated by Django 5.0.1 on 2026-01-28 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0024_plotfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmirrigation',
            name='foundation_pruning_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmirrigation',
            name='fruit_pruning_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmirrigation',
            name='last_harvesting_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmirrigation',
            name='plantation_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
